-- ============================================================================
-- QUARTIERS (niveau atomique sous l'AREA). Source : docs/migrationGood.csv
-- (onglet « Territoires » du BIG FIVE KPI UPDATE, fourni par Friesland) —
-- un quartier par ligne, découpe curée à la main (ASSAB→6, SBRE→12, etc.).
--
-- Modèle : territoire > area (table `zone`, clé métier (territoire_code, code))
-- > quartier (ici). L'area `zone` reste inchangée (back-compat PDV/mobile :
-- pdv.area_code = zone.code, useReferentiels.areas). Distributeur au niveau
-- territoire/area (zone_distributeur) — pas dupliqué ici.
--
-- Idempotent. Dépend de 20260630120000 (géographie) et 20260716150000
-- (zone_distributeur). 841 quartiers sur 176 areas.
-- Résolution zone par (territoire_code, area_code) ; territoire_code déduit du
-- nom via docs/big-five-kpi-csv/territory.csv.
-- ============================================================================
begin;

-- 0. Dédoublonnage `zone` : une seule area en double exacte (ANY/CÄTEAU),
--    sinon le join quartier→zone attacherait chaque quartier deux fois.
update zone_distributeur zd set zone_id = k.keep_id
from (select id, first_value(id) over (partition by territoire_code, code, nom order by id) keep_id,
             row_number() over (partition by territoire_code, code, nom order by id) rn from zone) k
where k.id = zd.zone_id and k.rn > 1
  and not exists (select 1 from zone_distributeur x where x.zone_id = k.keep_id and x.distributeur_id = zd.distributeur_id);
delete from zone_distributeur zd using (
  select id from (select id, row_number() over (partition by territoire_code, code, nom order by id) rn from zone) t where rn > 1
) dup where zd.zone_id = dup.id;
delete from zone z using (
  select id from (select id, row_number() over (partition by territoire_code, code, nom order by id) rn from zone) t where rn > 1
) dup where z.id = dup.id;

-- 1. Table quartier.
create table if not exists public.quartier (
  id serial primary key,
  zone_id integer not null references public.zone(id) on delete cascade,
  nom text not null,
  ordre integer not null default 1,
  unique (zone_id, nom)
);
create index if not exists quartier_zone_idx on public.quartier(zone_id);

-- 2. RLS : lecture authentifiée, écriture gestionnaire (admin/superviseur).
alter table public.quartier enable row level security;
drop policy if exists quartier_authenticated_read on public.quartier;
create policy quartier_authenticated_read on public.quartier
  for select to authenticated using (true);
drop policy if exists quartier_manager_write on public.quartier;
create policy quartier_manager_write on public.quartier
  for all to authenticated
  using (public.est_gestionnaire_perfect_store())
  with check (public.est_gestionnaire_perfect_store());

-- 3. Seed. Résolution zone par (territoire_code, area_code). Idempotent.
insert into public.quartier(zone_id, nom, ordre)
select z.id, v.nom, v.ordre
from (values
  ('BIN','NVEG','NOUVEAU GOUDRON',1),
  ('BIN','NVEG','FEH KESSE',2),
  ('BIN','NVEG','CITE SIR',3),
  ('BIN','NVEG','AKANDJE',4),
  ('BIN','NVEG','LAURIER 15',5),
  ('BIN','NVEG','SANTE',6),
  ('BIN','BLAN','BLANCHON',1),
  ('BIN','BLAN','PALMERAIE BINGERVILLE',2),
  ('BIN','BLAN','ADJAME BINGERVILLE',3),
  ('BIN','BLAN','BREGBO',4),
  ('BIN','BLAN','AKOUAI SANTE',5),
  ('BIN','BLAN','AMAN',6),
  ('BIN','BCIE','BASE CIE',1),
  ('BIN','BCIE','KOROCOBOUGOU',2),
  ('BIN','BCIE','GBAGBA',3),
  ('BIN','BCIE','BERLIN',4),
  ('BIN','BCIE','SAVANE',5),
  ('BIN','BCIE','MACHOU',6),
  ('BIN','BCIE','SICOGI',7),
  ('BIN','BCIE','MACHOUX',8),
  ('BIN','BCIE','MARCHE',9),
  ('BIN','ABAT','ABATTA',1),
  ('BIN','ABAT','ABATTA VILLAGE',2),
  ('BIN','ABAT','JULES VERNE',3),
  ('BIN','ABAT','CITE DU PORT',4),
  ('BIN','BING','TOUT BINGERVILLE',1),
  ('COC 1','LCET','LYCEE TECHNIQUE',1),
  ('COC 1','LCET','VALLON',2),
  ('COC 1','LCET','COLOMBIE',3),
  ('COC 1','MAHO','MAHOU COLOMBIE',1),
  ('COC 1','PERL','PERLE',1),
  ('COC 1','PERL','MAHOU',2),
  ('COC 1','PERL','ANGRE',3),
  ('COC 1','PALM','PALMERAIE',1),
  ('COC 1','PALM','ATTOBAN',2),
  ('COC 1','PALM','BONOUMIN',3),
  ('COC 1','PALM2','PALMERAIE2 COCOVICO',1),
  ('COC 1','ANGR','ANGRE 2PLATEAUX 7 TRANCHE',1),
  ('COC 1','DJOR','BESSIKOI',1),
  ('COC 1','DJOR','DJOROBITE',2),
  ('COC 2','DNGA','DANGA',1),
  ('COC 2','DNGA','COCODY CENTRE',2),
  ('COC 2','DNGA','BLAUKOSS',3),
  ('COC 2','BLKH','BLAUKOSS COCODY CENTRE',1),
  ('COC 2','RVER2','RIVIERA 2',1),
  ('COC 2','RVER2','RIVIERA 3',2),
  ('COC 2','RVER2','GOLF',3),
  ('COC 2','ANON','ANONO',1),
  ('COC 2','FAYB','FAYA BON PRIX',1),
  ('COC 2','FAYB','ABATTA',2),
  ('COC 2','CIAD','CIAD',1),
  ('COC 2','CIAD','MPOUTO',2),
  ('COC 2','CIAD','SYNACACI',3),
  ('COC 2','CIAD','FAYA (COTE ECHANGEUR)',4),
  ('TRE','ARAS','ARAS',1),
  ('TRE','ARAS','BELLEVILLE',2),
  ('TRE','ARAS','BIAFRA',3),
  ('TRE','ARAS','QUARTIER APOLLO',4),
  ('TRE','ARAS','ZONE 3',5),
  ('TRE','BIAF','ARAS',1),
  ('TRE','BIAF','BELLEVILLE',2),
  ('TRE','BIAF','BIAFRA',3),
  ('TRE','BIAF','QUARTIER APOLLO',4),
  ('TRE','BIAF','ZONE 3',5),
  ('MAR','RSD','RÉSIDENTIEL',1),
  ('MAR','RSD','CHAMPROUX',2),
  ('MAR','RSD','GROUPEMENT',3),
  ('MAR','RSD','HIBISCUS',4),
  ('MAR','RSD','MASSARANA',5),
  ('MAR','SICOG','SICOGI',1),
  ('MAR','SICOG','REMBLAIS',2),
  ('MAR','SICOG','ANOUMANBO',3),
  ('MAR','SICOG','SANS FIL',4),
  ('MAR','SICOG','ZONE 4',5),
  ('MAR','HIBI','RÉSIDENTIEL',1),
  ('MAR','HIBI','CHAMPROUX',2),
  ('MAR','HIBI','GRPE',3),
  ('MAR','HIBI','HIBISCUS',4),
  ('MAR','HIBI','MASSARANA',5),
  ('MAR','HIBI','SICOGI',6),
  ('MAR','HIBI','REMBLAIS',7),
  ('MAR','HIBI','ANOUMANBO',8),
  ('MAR','HIBI','SANS FIL',9),
  ('MAR','HIBI','ZONE4',10),
  ('KOU','RBLA','REMBLAIS',1),
  ('KOU','RBLA','MARAIS',2),
  ('KOU','RBLA','DIVO',3),
  ('KOU','RBLA','KOUMASSI 32',4),
  ('KOU','RBLA','TERM 05',5),
  ('KOU','CTE147','CITÉ 147',1),
  ('KOU','CTE147','PRODOMO',2),
  ('KOU','CTE147','SOPIM',3),
  ('KOU','CTE147','CAMPEMENT',4),
  ('KOU','CTE147','SOWETO',5),
  ('KOU','CTE147','SICOGI',6),
  ('KOU','AHOU','AHOUSSABOUGOU',1),
  ('KOU','AHOU','3 AMPOULES',2),
  ('KOU','AHOU','MARCHÉ DJE KONAN',3),
  ('KOU','AHOU','SOLEIL',4),
  ('KOU','AHOU','GELTI',5),
  ('KOU','KMSS32','REMBLAIS',1),
  ('KOU','KMSS32','MARAIS',2),
  ('KOU','KMSS32','DIVO',3),
  ('KOU','KMSS32','KOUMASSI 32',4),
  ('KOU','KMSS32','TERM 05',5),
  ('KOU','KMSS32','3 AMPOULES',6),
  ('KOU','KMSS32','AHOUSSABOUGOU',7),
  ('KOU','PRDM','CITÉ 147',1),
  ('KOU','PRDM','PRODOMO',2),
  ('KOU','PRDM','SOPIM',3),
  ('KOU','PRDM','CAMPEMENT',4),
  ('KOU','PRDM','SOWETO',5),
  ('KOU','PRDM','SICOGI',6),
  ('KOU','PRDM','MARCHÉ DJE KONAN',7),
  ('KOU','PRDM','SOLEIL',8),
  ('PRB','PRBC','PORT BOUET CENTRE',1),
  ('PRB','PRBC','CITÉ POLICIÈRE',2),
  ('PRB','PRBC','PETIT BASSAM',3),
  ('PRB','PRBC','VRIDI',4),
  ('PRB','AERO','AÉROPORT',1),
  ('PRB','AERO','ADJAWUI',2),
  ('PRB','JANF','JEAN FOLLY',1),
  ('PRB','JANF','ADJOUFOU',2),
  ('PRB','TRCA','TERRE ROUGE',1),
  ('PRB','TRCA','CORRIDOR',2),
  ('PRB','TRCA','ANANI',3),
  ('PRB','PRBO','PORT BOUET',1),
  ('BAS','MOKE','MOCKEYVILLE',1),
  ('BAS','MOKE','UNIVERSITÉ AMÉRICAINE',2),
  ('BAS','MOKE','EDOUKOU MIEZAN',3),
  ('BAS','MOKE','QUARTIER ARTISANAL',4),
  ('BAS','MOKE','MODESTE',5),
  ('BAS','MOKE','ANANI',6),
  ('BAS','MOKE','MOOSOU 1',7),
  ('BAS','VETO','VETOCO',1),
  ('BAS','VETO','MOOSOU2',2),
  ('BAS','VETO','IMPERIAL',3),
  ('BAS','VETO','DOS',4),
  ('BAS','VETO','QUARTIER FRANCE',5),
  ('BAS','VETO','DIOULABOUGOU',6),
  ('BAS','VETO','AZURETI',7),
  ('BAS','ANAN','ANANI',1),
  ('BAS','ANAN','DOS',2),
  ('BAS','ANAN','DIOULABOUGO',3),
  ('BAS','ANAN','PETIT MARCHÉ',4),
  ('BAS','8KLO','8 KILOS',1),
  ('BAS','8KLO','YAOU',2),
  ('BAS','8KLO','CENTRE VILLE',3),
  ('BAS','8KLO','BEGNERI',4),
  ('BAS','8KLO','SAMO',5),
  ('BAS','8KLO','ASSINIE',6),
  ('BAS','YAOU','8 KILOS',1),
  ('BAS','YAOU','YAOU',2),
  ('BAS','YAOU','CENTRE VILLE',3),
  ('BAS','YAOU','BEGNERI',4),
  ('BAS','YAOU','SAMO',5),
  ('BAS','YAOU','ASSINIE',6),
  ('BAS','CTREV','8 KILOS',1),
  ('BAS','CTREV','YAOU',2),
  ('BAS','CTREV','CENTRE VILLE',3),
  ('BAS','CTREV','BEGNERI',4),
  ('ABO','DJELI','DJELIBA',1),
  ('ABO','DJELI','TP',2),
  ('ABO','DJELI','PARCERELLE',3),
  ('ABO','DJELI','KONAN KAN',4),
  ('ABO','DJELI','BOIS BLANC',5),
  ('ABO','DJELI','AYEBO',6),
  ('ABO','DJELI','ADAOU',7),
  ('ABO','DIATEK','DIATEKRO',1),
  ('ABO','DIATEK','SOKORA',2),
  ('ABO','DIATEK','CCE',3),
  ('ABO','DIATEK','WATTVILLE',4),
  ('ABO','DIATEK','BELLEVILLE',5),
  ('ABO','DIATEK','SOS',6),
  ('ABO','DIATEK','DOSOBAH',7),
  ('ABO','DIATEK','CITÉ KOUMI',8),
  ('ABO','DIATEK','LYCÉE',9),
  ('ABO','DIATEK','KRINDJABO',10),
  ('ABO','DIATEK','KOLAIWA',11),
  ('ABO','DIATEK','SANHOUMAN',12),
  ('ABO','AYME','AYAMÉ',1),
  ('ABO','AYME','EBIKRA',2),
  ('ABO','AYME','AKRESIE',3),
  ('ABO','AYME','N’ZIKRO',4),
  ('ABO','AYME','BABADOUGOU',5),
  ('ABO','AYME','EBOUÉ',6),
  ('ABO','AYME','ABY',7),
  ('ABO','AYME','ADJOUAN',8),
  ('ABO','AYME','MOYASSUÉ',9),
  ('ABO','AYME','AKAKRO',10),
  ('ABO','AYME','V1',11),
  ('ABO','AYME','V2',12),
  ('ABO','AYME','KRINDJABO',13),
  ('ABO','AYME','KASSIKRO',14),
  ('ABO','ADKE','ADIAKÉ',1),
  ('ABO','ADKE','ABOISSO',2),
  ('ABO','ADKE','AYAMÉ',3),
  ('ABO','ADKE','KRINDJABO',4),
  ('ABO','ADKE','NOÉ',5),
  ('ABO','ADKE','ASSE',6),
  ('ABO','ADKE','SOUMIÉ',7),
  ('ABO','ADKE','N''ZIKRO',8),
  ('ABO','ADKE','KOFFIKRO',9),
  ('ABO','ADKE','BABADOUGOU',10),
  ('ABO','ADKE','CARF AHENOUA',11),
  ('ABO','ADKE','ADAOU',12),
  ('PLA','AGBA','AGBAN VILLAGE',1),
  ('PLA','AGBA','CITE FERMONT',2),
  ('PLA','AGBA','ATTECOUBE CENTRE',3),
  ('PLA','AGBA','PLATEAU CENTRE',4),
  ('PLA','AGBA','MARCHE DE FRUIT',5),
  ('PLA','CTEFER','AGBAN VILLAGE',1),
  ('PLA','CTEFER','CITE FERMONT',2),
  ('PLA','CTEFER','ATTECOUBE CENTRE',3),
  ('PLA','CTEFER','PLATEAU CENTRE',4),
  ('PLA','CTEFER','MARCHE DE FRUIT',5),
  ('YOP 1','ATTC','YOPOUGON 1 & 2',1),
  ('YOP 1','WASS','WASSAKARA',1),
  ('YOP 1','WASS','SELMER',2),
  ('YOP 1','WASS','SICOGI',3),
  ('YOP 1','SELM','WASSAKARA',1),
  ('YOP 1','SELM','SELMER',2),
  ('YOP 1','SELM','SICOGI',3),
  ('YOP 1','SBLE','YOPOUGON SABLE',1),
  ('YOP 1','SBLE','MILLIONNAIRE',2),
  ('YOP 1','SBLE','NOUVEAU QUARTIER',3),
  ('YOP 1','MILLI','YOPOUGON SABLE',1),
  ('YOP 1','MILLI','MILLIONNAIRE',2),
  ('YOP 1','MILLI','NOUVEAU QUARTIER',3),
  ('YOP 1','NGON','NIANGON NORD',1),
  ('YOP 1','NGON','SIDECI',2),
  ('YOP 1','TOROU','TOIT ROUGE',1),
  ('YOP 1','TOROU','LOKODJRO',2),
  ('YOP 1','TOROU','ATTECOUBE MOSSIKRO',3),
  ('YOP 1','LKOD','TOIT ROUGE',1),
  ('YOP 1','LKOD','LOKODJRO',2),
  ('YOP 1','LKOD','ATTECOUBE MOSSIKRO',3),
  ('YOP 2','NGOS','NIANGON SUD',1),
  ('YOP 2','NGOS','AZITO',2),
  ('YOP 2','AZTO','NIANGON SUD',1),
  ('YOP 2','AZTO','AZITO',2),
  ('YOP 2','KTE','KOUTÉ',1),
  ('YOP 2','KTE','PETIT TOIT ROUGE',2),
  ('YOP 2','KTE','BÉAGO',3),
  ('YOP 2','BEAG','KOUTÉ',1),
  ('YOP 2','BEAG','PETIT TOIT ROUGE',2),
  ('YOP 2','BEAG','BÉAGO',3),
  ('YOP 2','KWEI','KOWEIT',1),
  ('YOP 2','KWEI','SANTÉ',2),
  ('YOP 2','KWEI','ABOBO DOUMÉ',3),
  ('YOP 2','KWEI','AGBAYATÉ',4),
  ('YOP 2','YOPS','KOWEIT',1),
  ('YOP 2','YOPS','YOPOUGON SANTÉ',2),
  ('YOP 2','YOPS','ABOBO DOUMÉ',3),
  ('YOP 2','YOPS','AGBAYATÉ',4),
  ('YOP 3','ADKOI','ANDOKOI',1),
  ('YOP 3','ADKOI','UNIWAX',2),
  ('YOP 3','ADKOI','CRF ZONE',3),
  ('YOP 3','ADKOI','PRISON CIVILE',4),
  ('YOP 3','ADKOI','SODEFOR ET CITÉ ADO',5),
  ('YOP 3','ZNEIND','ZONE INDUSTRIELLE',1),
  ('YOP 3','ZNEIND','MICAO',2),
  ('YOP 3','ZNEIND','GESCO FOURRIÈRE',3),
  ('YOP 3','ZNEIND','PK22',4),
  ('YOP 3','ZNEIND','SIKENSI',5),
  ('YOP 3','ZNEIND','ATTINGUÉ',6),
  ('YOP 3','MCAO','ANDOKOI',1),
  ('YOP 3','MCAO','UNIWAX',2),
  ('YOP 3','MCAO','ZONE INDUSTRIELLE',3),
  ('YOP 3','MCAO','MICAO GESCO FOURRIÈRE',4),
  ('YOP 3','MCAO','PRISON CIVILE',5),
  ('YOP 3','MCAO','SODEFOR',6),
  ('YOP 3','MCAO','CITÉ ADO......',7),
  ('YOP 3','GSCO','ANDOKOI',1),
  ('YOP 3','GSCO','UNIWAX',2),
  ('YOP 3','GSCO','ZONE INDUSTRIELLE',3),
  ('YOP 3','GSCO','MICAO',4),
  ('YOP 3','GSCO','GESCO FOURRIÈRE',5),
  ('YOP 3','GSCO','PRISON CIVILE',6),
  ('YOP 3','GSCO','SODEFOR ET CITÉ ADO....',7),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','SIPOREX',1),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','BANCO2',2),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','ABOULAYE DIALLO',3),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','ANANERAIE',4),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','MAMIE ADJOUA',5),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','PORT BOUET 2',6),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','CRF CHU',7),
  ('YOP 3','SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','MOSQUÉE KOUDOUS',8),
  ('YOP 3','PRTBOU','PORT BOUET 2',1),
  ('YOP 3','PRTBOU','CRF CHU',2),
  ('YOP 3','PRTBOU','MOSQUÉE KOUDOUS',3),
  ('YOP 3','PRTBOU','ANANERAIE',4),
  ('YOP 3','PRTBOU','FUSCOM PORT BOUET 2',5),
  ('YOP 3','PRTBOU','RD POINT GESCO',6),
  ('YOP 3','AANERAIEANANERAI','ANANERAIE',1),
  ('YOP 3','AANERAIEANANERAI','GESCO RD POINT',2),
  ('YOP 3','AANERAIEANANERAI','BATIM',3),
  ('YOP 3','AANERAIEANANERAI','MAMIE ADJOUA',4),
  ('YOP 4','LBAFRIQUEJATARK','LUBAFRIQUE',1),
  ('YOP 4','LBAFRIQUEJATARK','JATARK',2),
  ('YOP 4','LBAFRIQUEJATARK','LOKOA',3),
  ('YOP 4','LBAFRIQUEJATARK','CITÉ VERTE',4),
  ('YOP 4','LBAFRIQUEJATARK','BAGNON',5),
  ('YOP 4','LBAFRIQUEJATARK','LIÈVRE ROUGE',6),
  ('YOP 4','LBAFRIQUEJATARK','KM17',7),
  ('YOP 4','LBAFRIQUEJATARK','BIMBRESSO',8),
  ('YOP 4','CNEO','MATY',1),
  ('YOP 4','CNEO','CANARI',2),
  ('YOP 4','CNEO','ANTENNE',3),
  ('YOP 4','CNEO','SICOGI ATTIÉ',4),
  ('YOP 4','CNEO','NIANGON À DROITE',5),
  ('YOP 4','CNEO','NIANGON CONTINUE',6),
  ('YOP 4','CNEO','CITÉ EECI',7),
  ('YOP 4','KBIM','KM17',1),
  ('YOP 4','KBIM','BIMBRESSO',2),
  ('YOP 4','KBIM','́JATARK',3),
  ('YOP 4','KBIM','LOKOA CITÉ VERTE',4),
  ('YOP 4','KBIM','LIÈVRE ROUGE',5),
  ('YOP 4','DCCO','SICOGI ATTIÉ',1),
  ('YOP 4','DCCO','ST ANDRÉ CÔTÉ DROIT',2),
  ('YOP 4','DCCO','PMI',3),
  ('YOP 4','DCCO','AIMÉ CESAIRE',4),
  ('YOP 4','DCCO','BON PRIX',5),
  ('YOP 4','DCCO','CRF BOBY & POLICIER CÔTÉ DROIT',6),
  ('YOP 4','DCCO','BAR ECLA',7),
  ('YOP 4','TRMINUSNUS','TERMINUS 47 SECTEUR DROIT',1),
  ('YOP 4','TRMINUSNUS','SICOGI PMI',2),
  ('YOP 4','TRMINUSNUS','TIKEN DJA',3),
  ('YOP 4','TRMINUSNUS','BMW',4),
  ('YOP 4','TRMINUSNUS','KIMI',5),
  ('YOP 4','AADÉMIEMIE','ACADÉMIE',1),
  ('YOP 4','AADÉMIEMIE','FIN GOUDRON',2),
  ('YOP 4','AADÉMIEMIE','PAYS BAS',3),
  ('YOP 4','AADÉMIEMIE','CAISTAB',4),
  ('YOP 4','AADÉMIEMIE','CITÉ LAURIER',5),
  ('YOP 4','AADÉMIEMIE','CITÉ VERTE',6),
  ('YOP 4','MROCAN','MAROC',1),
  ('YOP 4','MROCAN','ANANERAIE',2),
  ('YOP 4','MROCAN','PORT BOUET 2',3),
  ('YOP 4','MROCAN','LUBAFRIQUE',4),
  ('YOP 4','MROCAN','NIANGON À DROITE',5),
  ('YOP 4','MROCAN','TEXACO À DROITE',6),
  ('DAB','SNGONN','SONGON',1),
  ('DAB','SNGONN','N’DJEM',2),
  ('DAB','SNGONN','CARREFOUR JACQUESVILLE',3),
  ('DAB','SNGONN','JACQUESVILLE VILLE',4),
  ('DAB','SNGONN','DABOU',5),
  ('DAB','SNGONN','N’ZEKREZESSOU....',6),
  ('DAB','GANDLA','GRAND LAHOU',1),
  ('DAB','GANDLA','CRF GRAND LAHOU',2),
  ('DAB','GANDLA','CRF FRESCO',3),
  ('DAB','GANDLA','FRESCO VILLE ET PÉRIPHÉRIES',4),
  ('DAB','DBOUVI','DABOU VILLE',1),
  ('DAB','DBOUVI','SONGON',2),
  ('DAB','DBOUVI','CARREFOUR JACQUESVILLE....',3),
  ('DAB','SNGON','SONGON',1),
  ('DAB','SNGON','CARREFOUR JACQUESVILLE',2),
  ('DAB','SNGON','JACQUESVILLE',3),
  ('DAB','SNGON','DABOU',4),
  ('DAB','SNGON','GRAND LAHOU',5),
  ('DAB','SNGON','FRESCO',6),
  ('ABO 1','DKUI','DOKUI',1),
  ('ABO 1','DKUI','ANADOR',2),
  ('ABO 1','DKUI','COCO SERVICE DERRIÈRE UNIVERSITÉ ABOBO',3),
  ('ABO 1','DKUI','ADJAMÉ',4),
  ('ABO 1','DKUI','ALEPE',5),
  ('ABO 1','AOCATIERAVOCATIE','AVOCATIER',1),
  ('ABO 1','AOCATIERAVOCATIE','BC AUTOUTE',2),
  ('ABO 1','AOCATIERAVOCATIE','NOUVELLE GARE',3),
  ('ABO 1','AOCATIERAVOCATIE','AGNISSANKOI',4),
  ('ABO 1','AOCATIERAVOCATIE','BC',5),
  ('ABO 1','SMANKEKE','SAMANKE',1),
  ('ABO 1','SMANKEKE','KOLETCHA',2),
  ('ABO 1','SMANKEKE','ABOBO BAOULE',3),
  ('ABO 1','SMANKEKE','BIABOU',4),
  ('ABO 1','AEIKOIOI','AKEIKOI',1),
  ('ABO 1','AEIKOIOI','HABITAT',2),
  ('ABO 1','AEIKOIOI','AGBEKOI',3),
  ('ABO 1','AEIKOIOI','HOUPHOUT BOIGNY',4),
  ('ABO 1','LCEEMO','LYCEE MODERNE',1),
  ('ABO 1','LCEEMO','ETOILE',2),
  ('ABO 1','LCEEMO','GENDARMERIE',3),
  ('ABO 1','LCEEMO','BON PRIX GENDARMERIE',4),
  ('ABO 1','LCEEMO','CHATTONS',5),
  ('ABO 1','CTEPOL','CITE POLICIERE',1),
  ('ABO 1','CTEPOL','CAMP COMMANDO',2),
  ('ABO 1','CTEPOL','CNPS',3),
  ('ABO 1','CTEPOL','AVENUE KAZA',4),
  ('ABO 1','CTEPOL','COLATIER',5),
  ('ABO 1','AOBOGA','ABOBO GARE',1),
  ('ABO 1','AOBOGA','MAIRIE',2),
  ('ABO 2','MSQUEB','MOSQUE BLANCHE',1),
  ('ABO 2','MSQUEB','ANOKOUA KOUTE',2),
  ('ABO 2','MSQUEB','MARAHOUE',3),
  ('ABO 2','MSQUEB','AGRIPAC',4),
  ('ABO 2','MSQUEB','MOSQUE BLANCHE',5),
  ('ABO 2','MSQUEB','ANOKOUA KOUTE',6),
  ('ABO 2','MSQUEB','MARAHOUE',7),
  ('ABO 2','MSQUEB','AGRIPAC',8),
  ('ABO 2','SDECIO','SODECI',1),
  ('ABO 2','SDECIO','ONUCI',2),
  ('ABO 2','SDECIO','SOTRAPIM',3),
  ('ABO 2','SDECIO','CARREFOUR DIALLO',4),
  ('ABO 2','SDECIO','TAXI BAGAGE',5),
  ('ABO 2','SDECIO','SODECI',6),
  ('ABO 2','SDECIO','ONUCI',7),
  ('ABO 2','SDECIO','SOTRAPIM',8),
  ('ABO 2','SDECIO','CARREFOUR DIALLO',9),
  ('ABO 2','SDECIO','TAXI BAGAGE',10),
  ('ABO 2','CACOCC','CMA',1),
  ('ABO 2','CACOCC','COCCINELLE',2),
  ('ABO 2','CACOCC','CONCORDE',3),
  ('ABO 2','CACOCC','BOIS SEC',4),
  ('ABO 2','CACOCC','DELICE DE FRANCE',5),
  ('ABO 2','CACOCC','ANCIEN MARCHE',6),
  ('ABO 2','CACOCC','UNICAFE',7),
  ('ABO 2','CACOCC','FEU ENCIENNE GENDARMERIE',8),
  ('ANY','ACIENNE','ANCIENNE GENDARMERIE',1),
  ('ANY','ACIENNE','BELLE VILLE MORGUE',2),
  ('ANY','ACIENNE','GARE',3),
  ('ANY','ACIENNE','ADZOPE',4),
  ('ANY','ACIENNE','AGBOVILLE',5),
  ('ANY','CÄTEAU','CHÄTEAU',1),
  ('ANY','CÄTEAU','MARCHE COLA',2),
  ('ANY','CÄTEAU','MARCHE D''ANYAMA',3),
  ('ANY','CÄTEAU','DON ORION',4),
  ('ANY','CÄTEAU','AZAGUIE',5),
  ('ANY','CÄTEAU','BILDA AZAGUIE AWA ATTINGUE',6),
  ('ANY','CÄTEAU','CHÄTEAU',7),
  ('ANY','CÄTEAU','MARCHE COLA',8),
  ('ANY','CÄTEAU','MARCHE D''ANYAMA',9),
  ('ANY','CÄTEAU','DON ORION',10),
  ('ANY','CÄTEAU','MACHE CHAKA KONE',11),
  ('ANY','AYAMAP','ANYAMA',1),
  ('ANY','AYAMAP','PLAQUE ARABE',2),
  ('ANY','AYAMAP','ANYAMA RESIDENTIEL',3),
  ('ANY','AYAMAP','EBIMPE',4),
  ('ANY','AEAUTO','AXE AUTOROUTE N''DOTRE',1),
  ('ANY','AEAUTO','DANDI',2),
  ('ANY','AEAUTO','COMPLEXE',3),
  ('ANY','AEAUTO','MAIRIE',4),
  ('ANY','ANCGEN','ANCIENNE GENDARMERIE',1),
  ('ANY','ANCGEN','BELLE VILLE MORGUE',2),
  ('ANY','ANCGEN','GARE',3),
  ('ANY','BNDJIN1','BANDJI',1),
  ('ANY','BNDJIN1','N''DOTRE EXTENSION',2),
  ('ANY','BNDJIN1','CELESTE',3),
  ('ANY','BNDJIN1','NOUVELLE CASSE',4),
  ('ANY','BNDJIN1','ARC EN CIEL',5),
  ('ANY','BNDJIN1','DANDY',6),
  ('ANY','BNDJIN1','KOBAKRO',7),
  ('ANY','BNDJIN1','TERRE ROUGE',8),
  ('ANY','BNDJIN1','AKWABA',9),
  ('ANY','BNDJIN2','BANDJI',1),
  ('ANY','BNDJIN2','N''DOTRE EXTENSION',2),
  ('ANY','BNDJIN2','CELESTE',3),
  ('ANY','BNDJIN2','NOUVELLE CASSE',4),
  ('ANY','BNDJIN2','ARC EN CIEL',5),
  ('ANY','BNDJIN2','DANDY',6),
  ('ANY','BNDJIN2','KOBAKRO',7),
  ('ANY','BNDJIN2','TERRE ROUGE',8),
  ('ANY','BNDJIN2','AKWABA',9),
  ('ADJ','20LGTSLGTS','220LGTS',1),
  ('ADJ','20LGTSLGTS','LIBERTÉ',2),
  ('ADJ','20LGTSLGTS','QUARTIER LATIN',3),
  ('ADJ','20LGTSLGTS','BRACODI',4),
  ('ADJ','20LGTSLGTS','TERRASSE',5),
  ('ADJ','20LGTSLGTS','RENAULT',6),
  ('ADJ','WILLY','WILLIAMSVILLE',1),
  ('ADJ','WILLY','MACACI',2),
  ('ADJ','WILLY','PAILLET',3),
  ('ADJ','WILLY','VIDANGE',4),
  ('ADJ','WILLY','HMA',5),
  ('ADJ','SPEURP','SAPEUR POMPIER',1),
  ('ADJ','SPEURP','SAINT MICHEL',2),
  ('ADJ','SPEURP','QUARTIER EBRIÉ',3),
  ('ADJ','SPEURP','DALLAS',4),
  ('ADJ','NNGUIA','NANGUI ABROGOUA',1),
  ('ADJ','NNGUIA','MARCHE GOURO',2),
  ('ADJ','NNGUIA','BLACK MARKET',3),
  ('ADJ','NNGUIA','MIRADOR',4),
  ('ADJ','NNGUIA','NOUVELLE GARE',5),
  ('ADJ','BRAMA','BRAMACOTÉ',1),
  ('ADJ','BRAMA','DÉLÉGATION',2),
  ('ADJ','BRAMA','CITÉ RAN',3),
  ('ADJ','BRAMA','FORUM',4),
  ('ADJ','CNTREAD','TERRITOIRE ADJAMÉ',1),
  ('ADZ','AZOPEV','ADZOPE VILLE',1),
  ('ADZ','AKPEVI','AKOUPE',1),
  ('ADZ','AKPEVI','YAKASSE ATTOBROU',2),
  ('ADZ','AKPEVI','ANDE',3),
  ('ADZ','AKPEVI','YAKASSE ME',4),
  ('AGB','AGBVIL','AGBOVILLE VILLE',1),
  ('AGB','AGBVIL','N''DOUCI',2),
  ('AGB','AGBVIL','SIKENSI',3),
  ('AGB','AZGUVIL','AZAGUIE',1),
  ('AGB','AZGUVIL','PETIT YAPO',2),
  ('AGB','AZGUVIL','GRAND YAPO',3),
  ('AGB','AZGUVIL','RUBINO',4),
  ('AGB','AZGUVIL','SECHI',5),
  ('ABEN','CFETO','CAFETOUTOU',1),
  ('ABEN','CFETO','AGNIKRO',2),
  ('ABEN','CFETO','ADOUKOFFIKRO',3),
  ('ABEN','CFETO','GARE DE NIABLE',4),
  ('ABEN','CFETO','AFFALIKRO',5),
  ('ABEN','CFETO','ANGOUAKRO',6),
  ('ABEN','CFETO','DRAMANKRO',7),
  ('ABEN','CFETO','NIABLE',8),
  ('ABEN','CFETO','ADAOU',9),
  ('ABEN','CFETO','BAOULEKRO',10),
  ('ABEN','CMMER','COMMERCE',1),
  ('ABEN','CMMER','RELAIS',2),
  ('ABEN','CMMER','HKB',3),
  ('ABEN','CMMER','LOBIKRO',4),
  ('ABEN','CMMER','CAMP MILITAIRE',5),
  ('ABEN','CMMER','PLATEAU',6),
  ('ABEN','RSDT','RESIDENTIEL',1),
  ('ABEN','RSDT','120 LGMT',2),
  ('ABEN','RSDT','CHICAGO',3),
  ('ABEN','RSDT','BAOULEKRO',4),
  ('ABEN','RSDT','DIOULAKRO',5),
  ('ABEN','RSDT','GAGOU',6),
  ('ABEN','RSDT','OUELLE',7),
  ('ABEN','RSDT','GRAV D''OR',8),
  ('ABEN','RSDT','COMMERCE',9),
  ('ABEN','RSDT','KREGBE',10),
  ('ABEN','RSDT','SOSSOBOUGOU',11),
  ('ABEN','PLTEMI','ADAOU',1),
  ('ABEN','PLTEMI','ADOUKOFIKRO',2),
  ('ABEN','PLTEMI','BAOULEKRO',3),
  ('ABEN','PLTEMI','CAFETOU',4),
  ('ABEN','PLTEMI','AGNIKRO',5),
  ('ABEN','PLTEMI','CMP MILITAIRE',6),
  ('ABEN','PLTEMI','COMMERCE',7),
  ('ABEN','PLTEMI','DIOULAKRO',8),
  ('ABEN','PLTEMI','HKB',9),
  ('ABEN','PLTEMI','LOBKRO',10),
  ('ABEN','PLTEMI','PLATX',11),
  ('ABEN','PLTEMI','RELAIS',12),
  ('ABEN','GRELO','BONAHOUIN',1),
  ('ABEN','GRELO','ARRAH',2),
  ('ABEN','GRELO','BONGOUANOU',3),
  ('ABEN','GRELO','APRONPRON',4),
  ('ABEN','GRELO','ASSIKASSO',5),
  ('ABEN','GRELO','AGNIBILEKRO',6),
  ('ABEN','GRELO','ANDE',7),
  ('ABEN','GRELO','APKAOUSSOU',8),
  ('ABEN','GRELO','DAOUKRO',9),
  ('ABEN','GRELO','TANKESSE',10),
  ('ABEN','GRELO','ANUANSUE',11),
  ('YAM','BNON','Bonon',1),
  ('YAM','BNON','Garango',2),
  ('YAM','BNON','Gobazra',3),
  ('YAM','BNON','Bouaflé',4),
  ('YAM','BNON','Zougoussou',5),
  ('YAM','BNON','Zambakro',6),
  ('YAM','BNON','Zuenoula',7),
  ('YAM','Spim','Sopim',1),
  ('YAM','Spim','Makora - Belleville',2),
  ('YAM','Spim','Kokrenou 1',3),
  ('YAM','Spim','Kokrenou 2',4),
  ('YAM','Spim','Kokrenou 3',5),
  ('YAM','Spim','Kokenou 4',6),
  ('YAM','ASSAB','Assabou 1',1),
  ('YAM','ASSAB','Djahakro',2),
  ('YAM','ASSAB','50 & 227 logements',3),
  ('YAM','ASSAB','INPHB',4),
  ('YAM','ASSAB','Assabou 2',5),
  ('YAM','ASSAB','220 logements',6),
  ('YAM','DLABOU','Dioulabougou 1',1),
  ('YAM','DLABOU','Dioulabougou 2',2),
  ('YAM','DLABOU','Dioulabougou 3',3),
  ('YAM','DLABOU','Dioulabougou 4',4),
  ('YAM','DLABOU','Dioulabougou 5',5),
  ('YAM','DLABOU','Dioulabougou 6',6),
  ('YAM','MROFE','Morofé',1),
  ('YAM','MROFE','Morofé extention',2),
  ('YAM','MROFE','Morofé 2',3),
  ('YAM','MROFE','Morofé 3 -Habitat 1',4),
  ('YAM','MROFE','Habitat',5),
  ('DIM','TMOD','Toumodi',1),
  ('DIM','DMBKRV','Dimbokro ville',1),
  ('DIM','BCAND','Toumodi',1),
  ('DIM','BCAND','Dimbokro',2),
  ('DIM','BCAND','M''batto',3),
  ('DIM','BCAND','Bocanda',4),
  ('BKE 1','SKOURA','Sokoura',1),
  ('BKE 1','SKOURA','Commerce',2),
  ('BKE 1','SKOURA','Centre Ivoire',3),
  ('BKE 1','SKOURA','Houphouet-Ville',4),
  ('BKE 1','SKOURA','Nimbo',5),
  ('BKE 1','SKOURA','Djamourou',6),
  ('BKE 1','SKOURA','Dare_Salam',7),
  ('BKE 1','SKOURA','Tola',8),
  ('BKE 1','SKOURA','Maroc',9),
  ('BKE 1','KOKO','Koko',1),
  ('BKE 1','KOKO','Audjenekourani',2),
  ('BKE 1','KOKO','Hypodrome',3),
  ('BKE 1','KOKO','Beaufort',4),
  ('BKE 1','KOKO','Zone',5),
  ('BKE 1','KOKO','Gonvreville',6),
  ('BKE 1','KOKO','Beaufort',7),
  ('BKE 1','KOKO','Habitat Gonvreville',8),
  ('BKE 1','ONADKH','Cmrce',1),
  ('BKE 1','ONADKH','Sokoura',2),
  ('BKE 1','ONADKH','Marche',3),
  ('BKE 1','ONADKH','Boniere',4),
  ('BKE 1','ONADKH','Bokala',5),
  ('BKE 1','ONADKH','Dare salam',6),
  ('BKE 1','ONADKH','Belle ville',7),
  ('BKE 1','ONADKH','Air Frce',8),
  ('BKE 1','ONADKH','Djanbourou',9),
  ('BKE 1','ONADKH','Zone',10),
  ('BKE 1','ONADKH','Sakasou',11),
  ('BKE 1','ONADKH','Tola',12),
  ('BKE 1','CMRCE','Commerce',1),
  ('BKE 1','CMRCE','Nguattakro',2),
  ('BKE 1','CMRCE','Ahougnansou',3),
  ('BKE 1','CMRCE','Houphouet ville',4),
  ('BKE 1','CMRCE','Broukro',5),
  ('BKE 1','CMRCE','Sicogi',6),
  ('BKE 1','CMRCE','Ndakro',7),
  ('BKE 1','CMRCE','Campus',8),
  ('BKE 1','CMRCE','Adje yaokro',9),
  ('BKE 1','CMRCE','Tchelekro',10),
  ('BKE 1','BKEVILL','Bouaké ville',1),
  ('BKE 2','GRDM','Grand marche',1),
  ('BKE 2','GRDM','Nimbo',2),
  ('BKE 2','GRDM','Kennedi',3),
  ('BKE 2','GRDM','Sokoura',4),
  ('BKE 2','AIRFR','Air France 1,2,3',1),
  ('BKE 2','AIRFR','Corridor sud',2),
  ('BKE 2','DRSAL','Dares salam Djambourou',1),
  ('BKE 2','DRSAL','Abattoir',2),
  ('BKE 2','DRSAL','Laraba',3),
  ('BKE 2','DRSAL','Corridor Nord',4),
  ('BKE 2','BLLVIL','Belle ville 1,2,3',1),
  ('BKE 2','BLLVIL','Campement',2),
  ('KAT','GRDMA','Grand marche',1),
  ('KAT','GRDMA','Satama Sokora',2),
  ('KAT','GRDMA','Brobo',3),
  ('KAT','GRDMA','M''bahiakro',4),
  ('KAT','GRDMA','Niakara',5),
  ('KAT','GRDMA','Dabakala',6),
  ('KAT','KTLAVIL','Katiola ville',1),
  ('KOR','REBANQ','Commerce',1),
  ('KOR','REBANQ','Boulevard Ado',2),
  ('KOR','REBANQ','Voie kafoudal',3),
  ('KOR','REBANQ','Voie de Mbengue',4),
  ('KOR','REBANQ','Tarato',5),
  ('KOR','REBANQ','Siempurgo',6),
  ('KOR','REBANQ','Boundiali',7),
  ('KOR','REBANQ','Gbon',8),
  ('KOR','REBANQ','Kouto',9),
  ('KOR','REBANQ','Tengréla',10),
  ('KOR','QATAIRF','Quartier 14',1),
  ('KOR','QATAIRF','Air France',2),
  ('KOR','QATAIRF','Sinistré',3),
  ('KOR','QATAIRF','Sodepra',4),
  ('KOR','QATAIRF','Cite des medecins',5),
  ('KOR','QATAIRF','Tiékélézo',6),
  ('KOR','QATAIRF','Prémafolo',7),
  ('KOR','QATAIRF','Soba',8),
  ('KOR','QATAIRF','Kassirimé',9),
  ('KOR','HSSADG','Haoussadougou',1),
  ('KOR','HSSADG','Petit Paris',2),
  ('KOR','HSSADG','Soba',3),
  ('KOR','NVEQUA','Nouveau Quartier',1),
  ('KOR','NVEQUA','Sossorobougou',2),
  ('KOR','NVEQUA','Cocody',3),
  ('KOR','NVEQUA','Klofohakaha',4),
  ('FER','BNDLI','Boundiali & Environs',1),
  ('FER','FRKESS','Ferkessedougou & Environs SICAF1',1),
  ('FER','FRKESS','SICAF2',2),
  ('BON','BNAD','Bouna',1),
  ('BON','BNAD','Doropo',2),
  ('BON','BNAD','Tanda',3),
  ('BON','BNDOK1','Bondoukou 1',1),
  ('BON','BNDOK2','Bondoukou 2',1),
  ('DAL','Lbia','Labia',1),
  ('DAL','Lbia','Mossibougou',2),
  ('DAL','Lbia','Texas',3),
  ('DAL','Lbia','Huberson',4),
  ('DAL','Lbia','Millionnaire',5),
  ('DAL','Lbia','Soleil',6),
  ('DAL','Lbia','Kenedy2',7),
  ('DAL','Lbia','Suisse',8),
  ('DAL','Lbia','Grand marche',9),
  ('DAL','Lbia','ORLY',10),
  ('DAL','Lbia','Flora',11),
  ('DAL','ABTT','Abattoir',1),
  ('DAL','ABTT','Marche Manioc',2),
  ('DAL','ABTT','Garage',3),
  ('DAL','ABTT','Orly plateau',4),
  ('DAL','ABTT','Dioulabougou',5),
  ('DAL','CMERCE 1','Commerce',1),
  ('DAL','CMERCE 1','Kani',2),
  ('DAL','CMERCE 1','Mankono',3),
  ('DAL','CMERCE 1','Serela',4),
  ('DAL','CMERCE 1','Kouenahiri',5),
  ('MNK','CMERCE 2','Commerce',1),
  ('MNK','CMERCE 2','Kani',2),
  ('MNK','CMERCE 2','Mankona',3),
  ('MNK','DMDE','Diomande',1),
  ('MNK','DMDE','Traoré',2),
  ('MNK','DMDE','Rymer',3),
  ('MNK','DMDE','Quartier Grarge',4),
  ('MNK','DMDE','Garage Angola',5),
  ('MNK','DMDE','Sifie',6),
  ('MNK','DMDE','Kouego',7),
  ('MNK','SGULA','Séguéla',1),
  ('MNK','SGULA','Mankono',2),
  ('MNK','SGULA','Kani',3),
  ('MNK','SGULA','Dianra',4),
  ('MAN','MRCHE','Marche',1),
  ('MAN','MRCHE','Zele',2),
  ('MAN','MRCHE','Dayagoine',3),
  ('MAN','MRCHE','Municipal',4),
  ('MAN','MRCHE','Campus',5),
  ('MAN','MRCHE','Quartier thérèse',6),
  ('MAN','CAFOP','Cafop',1),
  ('MAN','CAFOP','Camp SEA',2),
  ('MAN','CAFOP','Lycée club',3),
  ('MAN','CAFOP','Commerce',4),
  ('MAN','CAFOP','Koko',5),
  ('MAN','CAFOP','Libreville',6),
  ('MAN','BKOUMA','Biankouma',1),
  ('MAN','BKOUMA','Bafing',2),
  ('MAN','BKOUMA','Touba',3),
  ('MAN','BKOUMA','Koro',4),
  ('MAN','BKOUMA','Complexe',5),
  ('MAN','BKOUMA','Sangouine',6),
  ('MAN','MANVI','Man ville',1),
  ('SOU','NBOUHI','Nanbouhi',1),
  ('SOU','NBOUHI','Camp manoir',2),
  ('SOU','NBOUHI','Chateau résidentiel',3),
  ('SOU','NBOUHI','Gabon',4),
  ('SOU','NBOUHI','Gbakalepa',5),
  ('SOU','NBOUHI','Yabayo',6),
  ('SOU','ANMANB','Anoumanbo',1),
  ('SOU','ANMANB','Hibiscus',2),
  ('SOU','ANMANB','Sicogi',3),
  ('SOU','ANMANB','Sans fil',4),
  ('SOU','ANMANB','Zone 4',5),
  ('SOU','ANMANB','KBF',6),
  ('SOU','SBRE','Okrouyo',1),
  ('SOU','SBRE','Guehio',2),
  ('SOU','SBRE','Buyo',3),
  ('SOU','SBRE','Bakayo',4),
  ('SOU','SBRE','osserie',5),
  ('SOU','SBRE','logboville',6),
  ('SOU','SBRE','Dapea',7),
  ('SOU','SBRE','lessirie',8),
  ('SOU','SBRE','commerce',9),
  ('SOU','SBRE','kpeiri',10),
  ('SOU','SBRE','opouyo',11),
  ('SOU','SBRE','cité ouvriere',12),
  ('SOU','ISSIA','Issia & Environs (mira, zobia, commerce, Saioua)',1),
  ('SPD','MNGA','Monogaga',1),
  ('SPD','MNGA','Dabiho',2),
  ('SPD','MNGA','Marche',3),
  ('SPD','MNGA','Doupoudou',4),
  ('SPD','GRDMRCH','Grand marche',1),
  ('SPD','GRDMRCH','Bereby',2),
  ('SPD','GRDMRCH','Commerce',3),
  ('SPD','CTE','Cité',1),
  ('SPD','CTE','Jule Ferry',2),
  ('SPD','CTE','Lac',3),
  ('SPD','CTE','Sewke',4),
  ('SPD','CTE','Bardot',5),
  ('SPD','JLESFE','Lac',1),
  ('SPD','JLESFE','Jules ferry',2),
  ('SPD','JLESFE','Zone industrielle',3),
  ('SPD','JLESFE','Bardot',4),
  ('SPD','CRDOR','Corridor',1),
  ('SPD','CRDOR','Gare',2),
  ('SPD','CRDOR','Sotref',3),
  ('SPD','CRDOR','Dafci',4),
  ('GAG 2','SLEIL','Zapata',1),
  ('GAG 2','SLEIL','Garahio',2),
  ('GAG 2','SLEIL','Babre',3),
  ('GAG 2','SLEIL','Soleil',4),
  ('GAG 2','SLEIL','Dioulabougou',5),
  ('GAG 2','CRDORS','Dares salam',1),
  ('GAG 2','CRDORS','Grarage Koffi',2),
  ('GAG 2','CRDORS','Garage Dosso',3),
  ('GAG 2','CRDORS','Corridor Sinfra',4),
  ('GAG 2','Ggnoa2','Gagnoa 2',1),
  ('GAG 2','Ggnoa2','Guiberoua',2),
  ('GAG 2','Ggnoa2','Issia',3),
  ('GAG 2','Ggnoa2','Gueyo',4),
  ('GAG 1','CMRCE','Commerce',1),
  ('GAG 1','CMRCE','Gbakayo',2),
  ('GAG 1','CMRCE','Galebre',3),
  ('GAG 1','CMRCE','Tchedelei',4),
  ('GAG 1','SLEIL','Soleil',1),
  ('GAG 1','SLEIL','Delbo',2),
  ('GAG 1','SLEIL','Millionnaire',3),
  ('GAG 1','SLEIL','Commerce',4),
  ('GAG 1','GBKY','Dioulabougou',1),
  ('GAG 1','GBKY','Katalina',2),
  ('GAG 1','GBKY','Commerce',3),
  ('GAG 1','GBKY','Gbakayo',4),
  ('DIV','SKOURA','Doukakou',1),
  ('DIV','SKOURA','Sokoura',2),
  ('DIV','SKOURA','Commerce',3),
  ('DIV','SKOURA','Bribore',4),
  ('DIV','LBANAIS','Konankro',1),
  ('DIV','LBANAIS','Libanais',2),
  ('DIV','LBANAIS','Jerusalem',3),
  ('DIV','LBANAIS','Dialogue 2',4),
  ('DIV','LBANAIS','Dioulabougou',5),
  ('DIV','DLOGUE1','Commerce',1),
  ('DIV','DLOGUE1','Dialogue 1',2),
  ('DIV','DLOGUE1','Gremian',3),
  ('DIV','DLOGUE1','Benoi',4),
  ('GUI 1','Giglo1N','Guiglo 1 nord',1),
  ('GUI 1','Giglo1S','Guiglo 1 sud',1),
  ('GUI 1','Giglo1DK','Guiglo 1',1),
  ('GUI 1','Giglo1DK','Duekoué',2),
  ('GUI 2','Giglo2N','Guiglo 2 Nord',1),
  ('GUI 2','Giglo2S','Guiglo 2 sud',1),
  ('GUI 2','Giglo2TBA','Guiglo 2',1),
  ('GUI 2','Giglo2TBA','Touba',2),
  ('ODI','ODNE1','Odiénne 1',1),
  ('ODI','ODNE2','Odiénne 2',1),
  ('ODI','SMTIGLA','Odiénne',1),
  ('ODI','SMTIGLA','Tiémé',2),
  ('ODI','SMTIGLA','Madinani',3),
  ('ODI','SMTIGLA','Samatiguila',4),
  ('Boun','NIBLCAMA','NI3-BLONTIARA',1),
  ('Boun','NIBLCAMA','DOROPO2-DASSIKELE',2),
  ('Boun','NIBLCAMA','BOBOSSO-ZONGO',3),
  ('Boun','NIBLCAMA','commerce',4),
  ('Boun','NIBLCAMA','TEFRO-BOUNA2',5),
  ('Boun','NIBLCAMA','CAMARASSO',6),
  ('Boun','BNGO','BOUNA',1),
  ('Boun','BNGO','BROMAKOTE-VARALE',2),
  ('Boun','BNGO','VARALE-DOROPO',3),
  ('Boun','BNGO','AXE BOUNA-VONKORO',4),
  ('Boun','BNGO','AXE BOUNA- MANGO',5)
) as v(terr, area, nom, ordre)
join public.zone z on z.territoire_code = v.terr and z.code = v.area
on conflict (zone_id, nom) do nothing;

commit;
