-- ============================================================================
-- Migration 1/4 : GÉOGRAPHIE  (onglet TERRITORY)
-- Hiérarchie : pays > région > sous-région > territoire > zone
-- 'nom_affichage' = nom commercial lisible (ex. SOUTH 1 REGION -> ABIDJAN 1)
-- (la colonne 'dist' de l'onglet était cassée -> #REF!, non reprise)
-- ============================================================================
begin;

create table if not exists pays (
  id   bigint generated always as identity primary key,
  code text not null unique,
  nom  text not null
);
create table if not exists region (
  id            bigint generated always as identity primary key,
  code          text not null unique,
  nom           text not null,
  nom_affichage text,
  pays_code     text not null references pays(code)
);
create table if not exists sous_region (
  id            bigint generated always as identity primary key,
  code          text not null unique,
  nom           text not null,
  nom_affichage text,
  region_code   text not null references region(code)
);
create table if not exists territoire (
  id              bigint generated always as identity primary key,
  code            text not null unique,
  nom             text not null unique,
  sous_region_code text not null references sous_region(code)
);
create table if not exists zone (
  id              bigint generated always as identity primary key,
  code            text,
  nom             text not null,
  territoire_code text not null references territoire(code)
);

insert into pays(code,nom) values
  ('CI1','Cote d''Ivoire')
on conflict (code) do nothing;

insert into region(code,nom,nom_affichage,pays_code) values
  ('SOUTHDIV','SOUTH DIVISION','ABIDJAN','CI1'),
  ('NORTHDIV','NORTH DIVISION','UP COUNTRY','CI1')
on conflict (code) do nothing;

insert into sous_region(code,nom,nom_affichage,region_code) values
  ('SOUTH1','SOUTH 1 REGION','ABIDJAN 1','SOUTHDIV'),
  ('SOUTH2','SOUTH 2 REGION','ABIDJAN 2','SOUTHDIV'),
  ('CNE','CENTRE-NORD -EST REGION','NORTH 1','NORTHDIV'),
  ('WEST','WEST REGION','NORTH 2','NORTHDIV')
on conflict (code) do nothing;

insert into territoire(code,nom,sous_region_code) values
  ('BIN','Bingerville','SOUTH1'),
  ('COC 1','Cocody 1','SOUTH1'),
  ('COC 2','Cocody 2','SOUTH1'),
  ('TRE','Treichville','SOUTH1'),
  ('MAR','Marcory','SOUTH1'),
  ('KOU','koumassi','SOUTH1'),
  ('PRB','Port bouet','SOUTH1'),
  ('BAS','Bassam','SOUTH1'),
  ('ABO','Aboisso','SOUTH1'),
  ('PLA','Plateau','SOUTH1'),
  ('YOP 1','Yopougon 1','SOUTH2'),
  ('YOP 2','Yopougon 2','SOUTH2'),
  ('YOP 3','Yopougon 3','SOUTH2'),
  ('YOP 4','Yopougon 4','SOUTH2'),
  ('DAB','Dabou','SOUTH2'),
  ('ABO 1','Abobo 1','SOUTH2'),
  ('ABO 2','Abobo 2','SOUTH2'),
  ('ANY','Anyama','SOUTH2'),
  ('ADJ','Adjame','SOUTH2'),
  ('ADZ','Adzope','SOUTH2'),
  ('AGB','Agboville','SOUTH2'),
  ('ABEN','Abengourou','CNE'),
  ('YAM','Yamoussoukro','CNE'),
  ('DIM','Dimbokro','CNE'),
  ('BKE 1','Bouake 1','CNE'),
  ('BKE 2','Bouake 2','CNE'),
  ('KAT','Katiola','CNE'),
  ('KOR','Korhogo','CNE'),
  ('FER','Ferke','CNE'),
  ('BON','Bondoukou','CNE'),
  ('DAL','Daloa','WEST'),
  ('MNK','Mankono','WEST'),
  ('MAN','Man','WEST'),
  ('SOU','Soubre','WEST'),
  ('SPD','San Pedro','WEST'),
  ('GAG 2','Gagnoa 2','WEST'),
  ('GAG 1','Gagnoa 1','WEST'),
  ('DIV','Divo','WEST'),
  ('GUI 1','Guiglo 1','WEST'),
  ('GUI 2','Guiglo 2','WEST'),
  ('ODI','Odienne','WEST'),
  ('Boun','Bouna','CNE')
on conflict (code) do nothing;

insert into zone(code,nom,territoire_code) values
  ('NVEG','NOUVEAU GOUDRON/ FEH KESSE/ CITE SIR/ AKANDJE/ LAURIER 15/SANTE','BIN'),
  ('BLAN','BLANCHON/PALMERAIE BINGERVILLE/ADJAME BINGERVILLE/ BREGBO/AKOUAI SANTE/AMAN/','BIN'),
  ('BCIE','BASE CIE/ KOROCOBOUGOU/GBAGBA/BERLIN/SAVANE/MACHOU/SICOGI/MACHOUX/MARCHE/','BIN'),
  ('ABAT','ABATTA/ABATTA VILLAGE/JULES VERNE/CITE DU PORT','BIN'),
  ('BING','TOUT BINGERVILLE','BIN'),
  ('LCET','LYCEE TECHNIQUE/VALLON/COLOMBIE','COC 1'),
  ('MAHO','MAHOU COLOMBIE','COC 1'),
  ('PERL','PERLE/MAHOU/ANGRE','COC 1'),
  ('PALM','PALMERAIE/ATTOBAN /BONOUMIN','COC 1'),
  ('PALM2','PALMERAIE2 COCOVICO','COC 1'),
  ('ANGR','ANGRE 2PLATEAUX 7 TRANCHE','COC 1'),
  ('DJOR','BESSIKOI/DJOROBITE','COC 1'),
  ('DNGA','DANGA/COCODY CENTRE/BLAUKOSS','COC 2'),
  ('BLKH','BLAUKOSS COCODY CENTRE','COC 2'),
  ('RVER2','RIVIERA 2/ RIVIERA 3/ GOLF','COC 2'),
  ('ANON','ANONO','COC 2'),
  ('FAYB','FAYA BON PRIX/ABATTA','COC 2'),
  ('CIAD','CIAD/MPOUTO/SYNACACI/FAYA (COTE ECHANGEUR)','COC 2'),
  ('ARAS','ARAS/ BELLEVILLE/ BIAFRA/ QUARTIER APOLLO / ZONE 3','TRE'),
  ('BIAF','ARAS/ BELLEVILLE/ BIAFRA/ QUARTIER APOLLO / ZONE 3','TRE'),
  ('RSD','RÉSIDENTIEL / CHAMPROUX / GROUPEMENT/ HIBISCUS / MASSARANA','MAR'),
  ('SICOG','SICOGI / REMBLAIS / ANOUMANBO/ SANS FIL / ZONE 4','MAR'),
  ('HIBI','RÉSIDENTIEL / CHAMPROUX / GRPE/ HIBISCUS / MASSARANA / SICOGI / REMBLAIS /ANOUMANBO/ SANS FIL/ ZONE4','MAR'),
  ('RBLA','REMBLAIS/MARAIS/ DIVO/ KOUMASSI 32/ TERM 05','KOU'),
  ('CTE147','CITÉ 147/ PRODOMO/SOPIM/ CAMPEMENT/SOWETO/SICOGI','KOU'),
  ('AHOU','AHOUSSABOUGOU/ 3 AMPOULES/ MARCHÉ DJE KONAN/SOLEIL/GELTI','KOU'),
  ('KMSS32','REMBLAIS/MARAIS/ DIVO/ KOUMASSI 32/ TERM 05 /3 AMPOULES / AHOUSSABOUGOU','KOU'),
  ('PRDM','CITÉ 147/ PRODOMO/SOPIM/ CAMPEMENT/SOWETO/SICOGI/ MARCHÉ DJE KONAN / SOLEIL','KOU'),
  ('PRBC','PORT BOUET CENTRE/CITÉ POLICIÈRE/PETIT BASSAM/VRIDI','PRB'),
  ('AERO','AÉROPORT/ ADJAWUI','PRB'),
  ('JANF','JEAN FOLLY/ ADJOUFOU','PRB'),
  ('TRCA','TERRE ROUGE/CORRIDOR/ANANI','PRB'),
  ('PRBO','PORT BOUET','PRB'),
  ('MOKE','MOCKEYVILLE/UNIVERSITÉ AMÉRICAINE/ EDOUKOU MIEZAN/QUARTIER ARTISANAL/MODESTE/ANANI/MOOSOU 1','BAS'),
  ('VETO','VETOCO/MOOSOU2/IMPERIAL/DOS/QUARTIER FRANCE/DIOULABOUGOU/AZURETI','BAS'),
  ('ANAN','ANANI/DOS/ DIOULABOUGO/PETIT MARCHÉ','BAS'),
  ('8KLO','8 KILOS/ YAOU/CENTRE VILLE/BEGNERI/SAMO/ASSINIE','BAS'),
  ('YAOU','8 KILOS/ YAOU/CENTRE VILLE/BEGNERI/SAMO/ASSINIE','BAS'),
  ('CTREV','8 KILOS/ YAOU/CENTRE VILLE/BEGNERI','BAS'),
  ('DJELI','DJELIBA /TP/ PARCERELLE/KONAN KAN/BOIS BLANC/ AYEBO/ADAOU','ABO'),
  ('DIATEK','DIATEKRO/SOKORA/CCE/WATTVILLE/BELLEVILLE/SOS/DOSOBAH/CITÉ KOUMI/LYCÉE/ KRINDJABO/KOLAIWA/SANHOUMAN','ABO'),
  ('AYME','AYAMÉ/EBIKRA/AKRESIE/N’ZIKRO/BABADOUGOU/EBOUÉ/ABY/ADJOUAN/MOYASSUÉ/AKAKRO/  V1/V2/KRINDJABO/KASSIKRO','ABO'),
  ('ADKE','ADIAKÉ/ABOISSO/AYAMÉ/ KRINDJABO/ NOÉ/ ASSE/SOUMIÉ/N''ZIKRO/ KOFFIKRO/BABADOUGOU/ CARF AHENOUA/ADAOU','ABO'),
  ('AGBA','AGBAN VILLAGE / CITE FERMONT / ATTECOUBE CENTRE / PLATEAU CENTRE / MARCHE DE FRUIT','PLA'),
  ('CTEFER','AGBAN VILLAGE / CITE FERMONT / ATTECOUBE CENTRE / PLATEAU CENTRE / MARCHE DE FRUIT','PLA'),
  ('ATTC','YOPOUGON 1 & 2','YOP 1'),
  ('WASS','WASSAKARA /  SELMER / SICOGI','YOP 1'),
  ('SELM','WASSAKARA /  SELMER / SICOGI','YOP 1'),
  ('SBLE','YOPOUGON SABLE / MILLIONNAIRE / NOUVEAU QUARTIER','YOP 1'),
  ('MILLI','YOPOUGON SABLE / MILLIONNAIRE / NOUVEAU QUARTIER','YOP 1'),
  ('NGON','NIANGON NORD / SIDECI','YOP 1'),
  ('TOROU','TOIT ROUGE / LOKODJRO / ATTECOUBE MOSSIKRO','YOP 1'),
  ('LKOD','TOIT ROUGE / LOKODJRO / ATTECOUBE MOSSIKRO','YOP 1'),
  ('NGOS','NIANGON SUD / AZITO','YOP 2'),
  ('AZTO','NIANGON SUD/ AZITO','YOP 2'),
  ('KTE','KOUTÉ/ PETIT TOIT ROUGE/ BÉAGO','YOP 2'),
  ('BEAG','KOUTÉ/ PETIT TOIT ROUGE/ BÉAGO','YOP 2'),
  ('KWEI','KOWEIT/ SANTÉ/ ABOBO DOUMÉ/ AGBAYATÉ','YOP 2'),
  ('YOPS','KOWEIT/ YOPOUGON SANTÉ/ ABOBO DOUMÉ/ AGBAYATÉ','YOP 2'),
  ('ADKOI','ANDOKOI/ UNIWAX/CRF ZONE /PRISON CIVILE/SODEFOR  ET CITÉ ADO','YOP 3'),
  ('ZNEIND','ZONE INDUSTRIELLE/ MICAO/GESCO FOURRIÈRE/ PK22/SIKENSI/ATTINGUÉ','YOP 3'),
  ('MCAO','ANDOKOI/ UNIWAX/ ZONE INDUSTRIELLE/ MICAO GESCO FOURRIÈRE/PRISON CIVILE/ SODEFOR/CITÉ ADO......','YOP 3'),
  ('GSCO','ANDOKOI/UNIWAX/ ZONE INDUSTRIELLE/ MICAO/ GESCO FOURRIÈRE/ PRISON CIVILE/ SODEFOR ET CITÉ ADO....','YOP 3'),
  ('SPOREXBANCO2/ ABOULAYE DIALLO/ ANANE','SIPOREX/ BANCO2/ ABOULAYE DIALLO/ ANANERAIE/ MAMIE ADJOUA/PORT BOUET 2/CRF CHU/MOSQUÉE KOUDOUS','YOP 3'),
  ('PRTBOU','PORT BOUET 2/CRF CHU/MOSQUÉE KOUDOUS/ ANANERAIE/ FUSCOM PORT BOUET 2/RD POINT GESCO','YOP 3'),
  ('AANERAIEANANERAI','ANANERAIE/ GESCO RD POINT/ BATIM/MAMIE ADJOUA','YOP 3'),
  ('LBAFRIQUEJATARK','LUBAFRIQUE/ JATARK/ LOKOA/CITÉ VERTE/BAGNON/ LIÈVRE ROUGE/KM17/BIMBRESSO/','YOP 4'),
  ('CNEO','MATY/CANARI /ANTENNE/ SICOGI ATTIÉ/NIANGON À DROITE/ NIANGON CONTINUE/ CITÉ EECI','YOP 4'),
  ('KBIM','KM17/BIMBRESSO/  ́JATARK/LOKOA CITÉ VERTE/ LIÈVRE ROUGE','YOP 4'),
  ('DCCO','SICOGI ATTIÉ/ST ANDRÉ CÔTÉ DROIT/ PMI/AIMÉ CESAIRE/BON PRIX/ CRF BOBY & POLICIER CÔTÉ DROIT/BAR ECLA','YOP 4'),
  ('TRMINUSNUS','TERMINUS 47 SECTEUR DROIT/ SICOGI PMI/ TIKEN DJA/BMW/KIMI','YOP 4'),
  ('AADÉMIEMIE','ACADÉMIE/ FIN GOUDRON/ PAYS BAS/CAISTAB/CITÉ LAURIER/ CITÉ VERTE','YOP 4'),
  ('MROCAN','MAROC/ANANERAIE/ PORT BOUET 2/LUBAFRIQUE/ NIANGON À DROITE /TEXACO À DROITE','YOP 4'),
  ('SNGONN','SONGON/N’DJEM/ CARREFOUR JACQUESVILLE/JACQUESVILLE VILLE/ DABOU/N’ZEKREZESSOU....','DAB'),
  ('GANDLA','GRAND LAHOU/CRF GRAND LAHOU/CRF FRESCO/FRESCO VILLE ET PÉRIPHÉRIES','DAB'),
  ('DBOUVI','DABOU VILLE/ SONGON/ CARREFOUR JACQUESVILLE....','DAB'),
  ('SNGON','SONGON/ CARREFOUR JACQUESVILLE/ JACQUESVILLE/ DABOU/GRAND LAHOU/FRESCO/','DAB'),
  ('DKUI','DOKUI / ANADOR / COCO SERVICE DERRIÈRE UNIVERSITÉ ABOBO/ADJAMÉ / ALEPE','ABO 1'),
  ('AOCATIERAVOCATIE','AVOCATIER / BC AUTOUTE / NOUVELLE GARE / AGNISSANKOI / BC','ABO 1'),
  ('SMANKEKE','SAMANKE / KOLETCHA / ABOBO BAOULE / BIABOU','ABO 1'),
  ('AEIKOIOI','AKEIKOI  / HABITAT  / AGBEKOI /  HOUPHOUT BOIGNY','ABO 1'),
  ('LCEEMO','LYCEE MODERNE / ETOILE / GENDARMERIE / BON PRIX GENDARMERIE / CHATTONS','ABO 1'),
  ('CTEPOL','CITE POLICIERE / CAMP COMMANDO / CNPS / AVENUE KAZA / COLATIER','ABO 1'),
  ('AOBOGA','ABOBO GARE  / MAIRIE','ABO 1'),
  ('MSQUEB','MOSQUE BLANCHE/ANOKOUA KOUTE/MARAHOUE/AGRIPAC','ABO 2'),
  ('MSQUEB','MOSQUE BLANCHE/ANOKOUA KOUTE/MARAHOUE/AGRIPAC','ABO 2'),
  ('SDECIO','SODECI/ONUCI/SOTRAPIM/CARREFOUR DIALLO/TAXI BAGAGE','ABO 2'),
  ('SDECIO','SODECI/ONUCI/SOTRAPIM/CARREFOUR DIALLO/TAXI BAGAGE','ABO 2'),
  ('CACOCC','CMA/COCCINELLE/CONCORDE/BOIS SEC/DELICE DE FRANCE / ANCIEN MARCHE/UNICAFE/FEU ENCIENNE GENDARMERIE','ABO 2'),
  ('ACIENNE','ANCIENNE GENDARMERIE/ BELLE VILLE MORGUE/ GARE /ADZOPE/AGBOVILLE','ANY'),
  ('CÄTEAU','CHÄTEAU/MARCHE COLA/MARCHE D''ANYAMA/DON ORION/AZAGUIE/BILDA AZAGUIE AWA ATTINGUE','ANY'),
  ('AYAMAP','ANYAMA/PLAQUE ARABE/ANYAMA RESIDENTIEL/EBIMPE/','ANY'),
  ('CÄTEAU','CHÄTEAU/MARCHE COLA/MARCHE D''ANYAMA/DON ORION/ MACHE CHAKA KONE','ANY'),
  ('AEAUTO','AXE AUTOROUTE N''DOTRE/ DANDI/COMPLEXE/MAIRIE','ANY'),
  ('ANCGEN','ANCIENNE GENDARMERIE/ BELLE VILLE MORGUE/ GARE','ANY'),
  ('BNDJIN1','BANDJI/N''DOTRE EXTENSION/CELESTE/NOUVELLE CASSE / ARC EN CIEL/DANDY/KOBAKRO/TERRE ROUGE/AKWABA','ANY'),
  ('BNDJIN2','BANDJI/N''DOTRE EXTENSION/CELESTE/NOUVELLE CASSE / ARC EN CIEL/DANDY/KOBAKRO/TERRE ROUGE/AKWABA','ANY'),
  ('20LGTSLGTS','220LGTS / LIBERTÉ / QUARTIER LATIN / BRACODI / TERRASSE/RENAULT','ADJ'),
  ('WILLY','WILLIAMSVILLE/MACACI/ PAILLET/VIDANGE/ HMA','ADJ'),
  ('SPEURP','SAPEUR POMPIER/ SAINT MICHEL/ QUARTIER EBRIÉ/DALLAS','ADJ'),
  ('NNGUIA','NANGUI ABROGOUA / MARCHE GOURO / BLACK MARKET / MIRADOR / NOUVELLE GARE','ADJ'),
  ('BRAMA','BRAMACOTÉ / DÉLÉGATION / CITÉ RAN / FORUM','ADJ'),
  ('CNTREAD','TERRITOIRE ADJAMÉ','ADJ'),
  ('AZOPEV','ADZOPE VILLE','ADZ'),
  ('AKPEVI','AKOUPE / YAKASSE ATTOBROU / ANDE / YAKASSE ME','ADZ'),
  ('AGBVIL','AGBOVILLE VILLE / N''DOUCI / SIKENSI','AGB'),
  ('AZGUVIL','AZAGUIE / PETIT YAPO / GRAND YAPO / RUBINO / SECHI','AGB'),
  ('CFETO','CAFETOUTOU/AGNIKRO/ADOUKOFFIKRO/GARE DE NIABLE /AFFALIKRO/ANGOUAKRO/DRAMANKRO/NIABLE/ADAOU/BAOULEKRO','ABEN'),
  ('CMMER','COMMERCE/RELAIS/HKB/LOBIKRO/CAMP MILITAIRE/PLATEAU','ABEN'),
  ('RSDT','RESIDENTIEL/120 LGMT/CHICAGO/BAOULEKRO/DIOULAKRO/GAGOU/OUELLE/GRAV D''OR/COMMERCE/KREGBE/SOSSOBOUGOU','ABEN'),
  ('PLTEMI','ADAOU/ADOUKOFIKRO/BAOULEKRO/CAFETOU/AGNIKRO/CMP MILITAIRE/COMMERCE/DIOULAKRO/HKB/LOBKRO/PLATX/RELAIS','ABEN'),
  ('GRELO','BONAHOUIN/ARRAH/BONGOUANOU/APRONPRON/ASSIKASSO/AGNIBILEKRO/ANDE/APKAOUSSOU/DAOUKRO/TANKESSE/ANUANSUE','ABEN'),
  ('BNON','Bonon / Garango / Gobazra / Bouaflé / Zougoussou / Zambakro / Zuenoula','YAM'),
  ('Spim','Sopim / Makora - Belleville / Kokrenou 1 / Kokrenou 2 / Kokrenou 3 / Kokenou 4','YAM'),
  ('ASSAB','Assabou 1 - Djahakro - 50 & 227 logements - INPHB / Assabou 2 - 220 logements','YAM'),
  ('DLABOU','Dioulabougou 1 / Dioulabougou 2 / Dioulabougou 3 / Dioulabougou 4 / Dioulabougou 5/ Dioulabougou 6','YAM'),
  ('MROFE','Morofé / Morofé extention/ Morofé 2 / Morofé 3 -Habitat 1 / Habitat','YAM'),
  ('TMOD','Toumodi','DIM'),
  ('DMBKRV','Dimbokro ville','DIM'),
  ('BCAND','Toumodi / Dimbokro / M''batto / Bocanda','DIM'),
  ('SKOURA','Sokoura / Commerce / Centre Ivoire / Houphouet-Ville / Nimbo / Djamourou / Dare_Salam / Tola / Maroc','BKE 1'),
  ('KOKO','Koko / Audjenekourani / Hypodrome / Beaufort / Zone / Gonvreville / Beaufort/ Habitat Gonvreville','BKE 1'),
  ('ONADKH','Cmrce/Sokoura/Marche/Boniere/Bokala/Dare salam/Belle ville/Air Frce/Djanbourou/Zone/Sakasou/Tola','BKE 1'),
  ('CMRCE','Commerce/Nguattakro/Ahougnansou/Houphouet ville/Broukro/Sicogi/Ndakro/Campus/Adje yaokro/Tchelekro','BKE 1'),
  ('BKEVILL','Bouaké ville','BKE 1'),
  ('GRDM','Grand marche / Nimbo / Kennedi / Sokoura','BKE 2'),
  ('AIRFR','Air France 1,2,3 / Corridor sud','BKE 2'),
  ('DRSAL','Dares salam Djambourou / Abattoir / Laraba / Corridor Nord','BKE 2'),
  ('BLLVIL','Belle ville 1,2,3 / Campement','BKE 2'),
  ('GRDMA','Grand marche / Satama Sokora / Brobo / M''bahiakro/ Niakara / Dabakala','KAT'),
  ('KTLAVIL','Katiola ville','KAT'),
  ('REBANQ','Commerce/Boulevard Ado/Voie kafoudal/Voie de Mbengue/Tarato/Siempurgo/Boundiali/Gbon/Kouto/Tengréla','KOR'),
  ('QATAIRF','Quartier 14/Air France/ Sinistré/Sodepra/Cite des medecins/Tiékélézo/Prémafolo/Soba/Kassirimé','KOR'),
  ('HSSADG','Haoussadougou / Petit Paris / Soba','KOR'),
  ('NVEQUA','Nouveau Quartier / Sossorobougou / Cocody /Klofohakaha','KOR'),
  ('BNDLI','Boundiali & Environs','FER'),
  ('FRKESS','Ferkessedougou & Environs SICAF1 /SICAF2','FER'),
  ('BNAD','Bouna / Doropo / Tanda','BON'),
  ('BNDOK1','Bondoukou 1','BON'),
  ('BNDOK2','Bondoukou 2','BON'),
  ('Lbia','Labia/Mossibougou/Texas/Huberson/ Millionnaire/Soleil/Kenedy2/Suisse/Grand marche/ORLY / Flora','DAL'),
  ('ABTT','Abattoir/Marche Manioc/Garage/Orly plateau/Dioulabougou','DAL'),
  ('CMERCE 1','Commerce / Kani / Mankono / Serela / Kouenahiri','DAL'),
  ('CMERCE 2','Commerce / Kani   / Mankona','MNK'),
  ('DMDE','Diomande / Traoré / Rymer / Quartier Grarge / Garage Angola / Sifie / Kouego','MNK'),
  ('SGULA','Séguéla/ Mankono / Kani / Dianra','MNK'),
  ('MRCHE','Marche / Zele / Dayagoine / Municipal / Campus / Quartier thérèse /','MAN'),
  ('CAFOP','Cafop / Camp SEA / Lycée club / Commerce / Koko / Libreville /','MAN'),
  ('BKOUMA','Biankouma / Bafing / Touba / Koro / Complexe / Sangouine /','MAN'),
  ('MANVI','Man ville','MAN'),
  ('NBOUHI','Nanbouhi/Camp manoir/Chateau résidentiel/Gabon/Gbakalepa/Yabayo','SOU'),
  ('ANMANB','Anoumanbo/Hibiscus/Sicogi/Sans fil/Zone 4/KBF','SOU'),
  ('SBRE','Okrouyo- Guehio -Buyo -Bakayo-osserie-logboville-Dapea-lessirie-commerce-kpeiri-opouyo-cité ouvriere','SOU'),
  ('ISSIA','Issia & Environs (mira, zobia, commerce, Saioua)','SOU'),
  ('MNGA','Monogaga / Dabiho / Marche / Doupoudou','SPD'),
  ('GRDMRCH','Grand marche / Bereby / Commerce','SPD'),
  ('CTE','Cité / Jule Ferry / Lac / Sewke / Bardot','SPD'),
  ('JLESFE','Lac / Jules ferry / Zone industrielle / Bardot','SPD'),
  ('CRDOR','Corridor / Gare / Sotref / Dafci','SPD'),
  ('SLEIL','Zapata / Garahio / Babre / Soleil / Dioulabougou','GAG 2'),
  ('CRDORS','Dares salam / Grarage Koffi / Garage Dosso / Corridor Sinfra','GAG 2'),
  ('Ggnoa2','Gagnoa 2 / Guiberoua / Issia / Gueyo','GAG 2'),
  ('CMRCE','Commerce / Gbakayo / Galebre / Tchedelei','GAG 1'),
  ('SLEIL','Soleil / Delbo / Millionnaire / Commerce','GAG 1'),
  ('GBKY','Dioulabougou / Katalina / Commerce / Gbakayo','GAG 1'),
  ('SKOURA','Doukakou / Sokoura / Commerce / Bribore','DIV'),
  ('LBANAIS','Konankro / Libanais / Jerusalem / Dialogue 2 / Dioulabougou','DIV'),
  ('DLOGUE1','Commerce / Dialogue 1 / Gremian / Benoi','DIV'),
  ('Giglo1N','Guiglo 1 nord','GUI 1'),
  ('Giglo1S','Guiglo 1 sud','GUI 1'),
  ('Giglo1DK','Guiglo 1 / Duekoué','GUI 1'),
  ('Giglo2N','Guiglo 2 Nord','GUI 2'),
  ('Giglo2S','Guiglo 2 sud','GUI 2'),
  ('Giglo2TBA','Guiglo 2 / Touba','GUI 2'),
  ('ODNE1','Odiénne 1','ODI'),
  ('ODNE2','Odiénne 2','ODI'),
  ('SMTIGLA','Odiénne / Tiémé / Madinani / Samatiguila','ODI'),
  ('NIBLCAMA','NI3-BLONTIARA/DOROPO2-DASSIKELE/BOBOSSO-ZONGO/commerce /TEFRO-BOUNA2/CAMARASSO','Boun'),
  ('BNGO','BOUNA /BROMAKOTE-VARALE/VARALE-DOROPO/AXE BOUNA-VONKORO/AXE BOUNA- MANGO','Boun')
on conflict do nothing;

commit;